Fixed remarks and finished backend part
Mavlyudabegim/budgetify pull request #5
Opened 2022-03-25 20:32 UTC by Mavlyudabegim

In this PR I implemented authentication, registration logic using jwt, bcrypt
As well I added subscription logic
I fixed previous remarks

2022-03-26 06:49 UTC, Lokki17 requested changes
Fix remarks and merge

2022-03-26 06:49 UTC, Lokki17 commented on server/controllers/userController.js
> +    const userData = await userService.login(req.body.email, req.body.password);
Why do you pass refresh token in cookies and as part of body?

2022-03-26 06:49 UTC, Lokki17 commented on server/controllers/userController.js
> +    const token = await userService.logout(refreshToken);
Why do you return token on logout?

2022-03-26 06:49 UTC, Lokki17 commented on server/controllers/userController.js
> +async function refresh(req, res, next) {
What does this method?

2022-03-26 15:45 UTC, Mavlyudabegim commented on server/controllers/userController.js
> +    const userData = await userService.login(req.body.email, req.body.password);
I wanted to save refresh token in httpOnly cookie

2022-03-26 15:51 UTC, Mavlyudabegim commented on server/controllers/userController.js
> +async function refresh(req, res, next) {
This methods gets request cookie and removes it from cookies.

2022-03-26 15:58 UTC, Mavlyudabegim commented on server/controllers/userController.js
> +    const userData = await userService.login(req.body.email, req.body.password);
I wanted to save refresh token in httpOnly cookie

2022-03-26 15:58 UTC, Mavlyudabegim commented on server/controllers/userController.js
> +async function refresh(req, res, next) {
This methods gets request cookie and removes it from cookies.

2022-03-26 15:58 UTC, Mavlyudabegim commented on server/controllers/userController.js
> +    const token = await userService.logout(refreshToken);
On order to remove refreshToken from cookie I get refreshToken from httpOnly cookie

2022-03-26 15:58 UTC, merged

2022-03-27 04:40 UTC, Lokki17 commented on server/controllers/userController.js
> +    const userData = await userService.login(req.body.email, req.body.password);
ok, why?

2022-03-27 04:43 UTC, Lokki17 commented on server/controllers/userController.js
> +    const token = await userService.logout(refreshToken);
I dont understand. Why do you need to store token in cookie?